import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

#1
df= sns.load_dataset('iris')

col=['sepal_length','sepal_width', 'pedal_length', 'pedal_width']
scol= df['species'].unique()
plt.figure(figsize=(16,12))
plt.subplot(4,2,1)
plt.plot(df[df['species']==scol[0]].sepal_length.values, label=scol[0], lw=3)
plt.plot(df[df['species']==scol[1]].sepal_length.values, label=scol[1], lw=3)
plt.plot(df[df['species']==scol[2]].sepal_length.values, label=scol[2], lw=3)
plt.grid()
plt.legend()
plt.xlabel('sepal length')
plt.ylabel('cm')
plt.subplot(4,2,2)
plt.plot(df[df['species']==scol[0]].sepal_width.values, label=scol[0], lw=3)
plt.plot(df[df['species']==scol[1]].sepal_width.values, label=scol[1], lw=3)
plt.plot(df[df['species']==scol[2]].sepal_width.values, label=scol[2], lw=3)
plt.grid()
plt.legend()
plt.xlabel('sepal width')
plt.ylabel('cm')
plt.subplot(4,2,3)
plt.plot(df[df['species']==scol[0]].petal_length.values, label=scol[0], lw=3)
plt.plot(df[df['species']==scol[1]].petal_length.values, label=scol[1], lw=3)
plt.plot(df[df['species']==scol[2]].petal_length.values, label=scol[2], lw=3)
plt.grid()
plt.legend()
plt.xlabel('petal length')
plt.ylabel('cm')
plt.subplot(4,2,4)
plt.plot(df[df['species']==scol[0]].petal_width.values, label=scol[0], lw=3)
plt.plot(df[df['species']==scol[1]].sepal_width.values, label=scol[1], lw=3)
plt.plot(df[df['species']==scol[2]].sepal_width.values, label=scol[2], lw=3)
plt.grid()
plt.legend()
plt.xlabel('petal width')
plt.ylabel('cm')
plt.subplot(4,2,5)
plt.hist(df[df['species']==scol[0]].sepal_length.values, label=scol[0], lw=3)
plt.hist(df[df['species']==scol[1]].sepal_length.values, label=scol[1], lw=3)
plt.hist(df[df['species']==scol[2]].sepal_length.values, label=scol[2], lw=3)
plt.grid()
plt.legend()
plt.xlabel('sepal length')
plt.ylabel('cm')
plt.subplot(4,2,6)
plt.hist(df[df['species']==scol[0]].sepal_width.values, label=scol[0], lw=3)
plt.hist(df[df['species']==scol[1]].sepal_width.values, label=scol[1], lw=3)
plt.hist(df[df['species']==scol[2]].sepal_width.values, label=scol[2], lw=3)
plt.grid()
plt.legend()
plt.xlabel('sepal width')
plt.ylabel('cm')
plt.subplot(4,2,7)
plt.hist(df[df['species']==scol[0]].petal_length.values, label=scol[0], lw=3)
plt.hist(df[df['species']==scol[1]].petal_length.values, label=scol[1], lw=3)
plt.hist(df[df['species']==scol[2]].petal_length.values, label=scol[2], lw=3)
plt.grid()
plt.legend()
plt.xlabel('petal length')
plt.ylabel('cm')
plt.subplot(4,2,8)
plt.hist(df[df['species']==scol[0]].petal_width.values, label=scol[0], lw=3)
plt.hist(df[df['species']==scol[1]].sepal_width.values, label=scol[1], lw=3)
plt.hist(df[df['species']==scol[2]].sepal_width.values, label=scol[2], lw=3)
plt.grid()
plt.legend()
plt.xlabel('petal width')
plt.ylabel('cm')
plt.show()